version: "3.7"

services:
  activemq:
    build: activemq/
    image: activemq:v1
    ports:
    - 8161:8161

  db:
    build: postgresql/
    ports:
    - 5432:5432
    environment:
      - POSTGRES_PASSWORD=x5
      - POSTGRES_DB=config-service-x5
    volumes:
    - ./postgresql/data:/var/lib/postgresql/data

